project: 
  type: website

website: 
  page-navigation: true
  title: "Biostatistics!" 
  description: "Does this work"
  site-url: "https://jsgosnell.github.io/cuny_biostats_book/" 
  repo-url: "https://github.com/jsgosnell/cuny_biostats_book"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC BY-NC-SA 4.0"  
  
  sidebar:
    background: "#D9E3E4"
    logo: images/image-from-rawpixel-id-547642-jpeg.jpg
    title: "Biostatistics: Concepts and approaches for collecting good data and 
  turning it into knowledge!" 
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.gosnelllab.com/
        text: "Gosnell lab website"
      - icon: github
        href: https://github.com/jsgosnell
        text: "J. Stephen Gosnell github"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Getting started"
        contents:
          - href: index.qmd
            text: Welcome
          - href: content/getting_started.qmd
            text: Before the first class
      - section: "Chapters"
        contents:
          - href: content/Introduction.qmd
            text: Introduction
          - href: content/Acquiring_data.qmd
            text: Acquiring data
          - href: content/chapters/summarizing_data.qmd
            text: Summarizing data 
          - href: content/Estimation.qmd
            text: Estimation
          - href: content/Probability.qmd
            text: Probability 
          - href: content/Binomial.qmd
            text: Hypothesis testing starting with binomial tests
          - href: content/Tests_for_continuous_data_from_one_sample.qmd
            text: Tests for continuous data from one sample
          - href: content/Compare_proportions_among_populations.qmd
            text: Compare proportions
          - href: content/chapters/Compare_means_among_populations.qmd
            text: Compare means among groups
          - href: content/chapters/More_ANOVAs.qmd
            text: More ANOVAs
          - href: content/chapters/Relationships_among_numerical_variables.qmd
            text: Relationships among numerical variables
          - href: content/acknowledgements.qmd
            text: Acknowledgements
          - href: content/additional_resources.qmd
            text: Additional resources        
          - href: content/references.bib
            text: Download a full reference list!
      - section: "Practice Problems"
        contents:
          - href: content/practice_problems/6_Comparing_means.qmd
            text: Compare means among groups
      - section: "Appendix"
        contents: 
          - href: content/Intro_to_R.qmd
            text: Getting started with R!
          - href: content/Intro_to_Rmd.Rmd
            text: Getting started with Rmarkdown!
          - href: content/Intro_to_ggplot2.qmd
            text: Getting started with ggpplot2!
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
